%% ========================================================================
% Plot_20km_Landslide_Overlap_Analysis.m
%
% PURPOSE
% -------------------------------------------------------------------------
% Publication-quality visualization of landslide overlap among the
% 21 stations for the 20-km radius analysis.
%
% INPUT:
% Station_Landslide_Counts_20km_ALLOW_OVERLAP.xlsx
% Station_Landslide_Metadata_20km_ALLOW_OVERLAP.xlsx
%
% FIGURES:
%
% Figure 1
%   (a) Multiplicity distribution:
%       Number of physical landslides associated with 1, 2, 3... stations
%
%   (b) Station-wise landslide composition:
%       station-specific + shared landslides
%
% Figure 2
%   Pairwise overlap matrix:
%       number of physical landslides shared between every pair of stations
%
% IMPORTANT
% -------------------------------------------------------------------------
% Catalogue duplicates have already been removed.
%
% "Shared" here means:
% the SAME unique physical landslide occurs within 20 km of more than
% one station and is therefore intentionally used for each relevant site.
%
% ========================================================================

clc;
clear;
close all;


%% ========================================================================
% 1. PATHS
%% ========================================================================

ROOT = ...
    fullfile(neh_root(),'step_0_landslide_filtering');


COUNT_FILE = fullfile( ...
    ROOT, ...
    'Station_Landslide_Counts_20km_ALLOW_OVERLAP.xlsx');


META_FILE = fullfile( ...
    ROOT, ...
    'Station_Landslide_Metadata_20km_ALLOW_OVERLAP.xlsx');


OUT_DIR = fullfile( ...
    ROOT, ...
    '20km_overlap_figures');


if ~exist(OUT_DIR,'dir')
    mkdir(OUT_DIR);
end


%% ========================================================================
% 2. READ DATA
%% ========================================================================

Counts = readtable( ...
    COUNT_FILE, ...
    'Sheet','Station_counts', ...
    'VariableNamingRule','preserve');


Global = readtable( ...
    COUNT_FILE, ...
    'Sheet','Global_audit', ...
    'VariableNamingRule','preserve');


Pairs = readtable( ...
    META_FILE, ...
    'Sheet','Station_event_pairs', ...
    'VariableNamingRule','preserve');


%% ========================================================================
% 3. BASIC VARIABLES
%% ========================================================================

Station = string(Counts.Station);

Total = Counts.Events_within_20km;

UniqueOnly = ...
    Counts.Events_unique_to_this_station_buffer;

Shared = ...
    Counts.Events_also_within_other_station_buffers;


nStations = height(Counts);


%% ========================================================================
% 4. RECONSTRUCT UNIQUE PHYSICAL EVENT IDs
%
% Same event =
% same date + longitude + latitude.
%% ========================================================================

eventDate = Pairs.EventDate;


if ~isdatetime(eventDate)

    eventDate = datetime( ...
        eventDate);

end


lat = double(Pairs.Latitude);

lon = double(Pairs.Longitude);


eventKey = ...
    compose('%04d%02d%02d', ...
    year(eventDate), ...
    month(eventDate), ...
    day(eventDate)) + "_" + ...
    compose('%.6f',lat) + "_" + ...
    compose('%.6f',lon);


[uniqueEventKey,~,eventGroup] = ...
    unique(eventKey,'stable');


nPhysicalEvents = ...
    numel(uniqueEventKey);


%% ========================================================================
% 5. NUMBER OF STATIONS ASSOCIATED WITH EACH PHYSICAL EVENT
%% ========================================================================

stationMultiplicity = ...
    zeros(nPhysicalEvents,1);


for e = 1:nPhysicalEvents

    idx = ...
        eventGroup == e;


    stationMultiplicity(e) = ...
        numel(unique(string(Pairs.Station(idx))));

end


%% ========================================================================
% 6. SUMMARY NUMBERS
%% ========================================================================

N_uniquePhysical = ...
    nPhysicalEvents;


N_sharedPhysical = ...
    sum(stationMultiplicity >= 2);


N_singleStation = ...
    sum(stationMultiplicity == 1);


N_stationAssignments = ...
    height(Pairs);


N_extraAssignments = ...
    N_stationAssignments - ...
    N_uniquePhysical;


pctSharedPhysical = ...
    100 * N_sharedPhysical / N_uniquePhysical;


maxMultiplicity = ...
    max(stationMultiplicity);


fprintf('\n');
fprintf('=============================================================\n');
fprintf(' 20-km LANDSLIDE OVERLAP SUMMARY\n');
fprintf('=============================================================\n');

fprintf( ...
    'Unique physical landslides       : %d\n', ...
    N_uniquePhysical);

fprintf( ...
    'Single-station landslides        : %d\n', ...
    N_singleStation);

fprintf( ...
    'Shared physical landslides       : %d\n', ...
    N_sharedPhysical);

fprintf( ...
    'Shared physical landslides       : %.1f %%\n', ...
    pctSharedPhysical);

fprintf( ...
    'Total station-event assignments  : %d\n', ...
    N_stationAssignments);

fprintf( ...
    'Extra assignments due to overlap : %d\n', ...
    N_extraAssignments);

fprintf( ...
    'Maximum stations sharing event   : %d\n', ...
    maxMultiplicity);

fprintf('=============================================================\n\n');


%% ========================================================================
% 7. HISTOGRAM DATA
%% ========================================================================

multiplicityLevels = ...
    1:maxMultiplicity;


multiplicityCount = ...
    zeros(size(multiplicityLevels));


for k = 1:numel(multiplicityLevels)

    multiplicityCount(k) = ...
        sum(stationMultiplicity == multiplicityLevels(k));

end


%% ========================================================================
% 8. SORT STATIONS FOR PROFESSIONAL BAR PLOT
%% ========================================================================

[~,order] = ...
    sort(Total,'descend');


StationSort = ...
    Station(order);


UniqueSort = ...
    UniqueOnly(order);


SharedSort = ...
    Shared(order);


TotalSort = ...
    Total(order);


%% ========================================================================
% FIGURE 1
% MULTIPLICITY + STATION-WISE OVERLAP
%% ========================================================================

fig1 = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 35 18], ...
    'Renderer','painters');


tl = tiledlayout( ...
    fig1, ...
    1,2, ...
    'TileSpacing','compact', ...
    'Padding','compact');


%% ========================================================================
% PANEL A -- EVENT MULTIPLICITY HISTOGRAM
%% ========================================================================

ax1 = nexttile(tl,1);


b1 = bar( ...
    ax1, ...
    multiplicityLevels, ...
    multiplicityCount, ...
    0.70, ...
    'FaceColor',[0.31 0.55 0.78], ...
    'EdgeColor','k', ...
    'LineWidth',0.9);


hold(ax1,'on');


%% ------------------------------------------------------------------------
% Count labels
%% ------------------------------------------------------------------------

for k = 1:numel(multiplicityLevels)

    if multiplicityCount(k) == 0
        continue
    end


    text( ...
        ax1, ...
        multiplicityLevels(k), ...
        multiplicityCount(k) + ...
        0.025*max(multiplicityCount), ...
        sprintf('%d',multiplicityCount(k)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',12, ...
        'FontWeight','bold', ...
        'Color','k');

end


xlabel( ...
    ax1, ...
    'Number of stations associated with a physical landslide', ...
    'FontSize',14, ...
    'FontWeight','bold');


ylabel( ...
    ax1, ...
    'Number of unique landslide events', ...
    'FontSize',14, ...
    'FontWeight','bold');


xticks( ...
    ax1, ...
    multiplicityLevels);


xlim( ...
    ax1, ...
    [0.4 maxMultiplicity+0.6]);


ylim( ...
    ax1, ...
    [0 max(multiplicityCount)*1.15]);


set( ...
    ax1, ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor','k', ...
    'YColor','k');


grid(ax1,'on');

ax1.GridLineStyle = ':';

ax1.GridAlpha = 0.15;


text( ...
    ax1, ...
    0.02, ...
    0.98, ...
    '(a)', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',16, ...
    'FontWeight','bold');


%% ========================================================================
% PANEL B -- STATION-WISE STACKED BAR
%% ========================================================================

ax2 = nexttile(tl,2);


Y = [ ...
    UniqueSort ...
    SharedSort];


barh( ...
    ax2, ...
    Y, ...
    'stacked', ...
    'BarWidth',0.72);


hold(ax2,'on');


% Set restrained professional colours
bb = findobj(ax2,'Type','Bar');


% MATLAB returns reverse order
if numel(bb) >= 2

    bb(2).FaceColor = [0.72 0.83 0.92];
    bb(2).EdgeColor = 'k';

    bb(1).FaceColor = [0.86 0.42 0.34];
    bb(1).EdgeColor = 'k';

end


set( ...
    ax2, ...
    'YDir','reverse', ...
    'YTick',1:nStations, ...
    'YTickLabel',StationSort, ...
    'FontSize',11.5, ...
    'FontWeight','bold', ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor','k', ...
    'YColor','k');


xlabel( ...
    ax2, ...
    'Number of landslide events within 20 km', ...
    'FontSize',14, ...
    'FontWeight','bold');


%% ------------------------------------------------------------------------
% Add total count at end of each bar
%% ------------------------------------------------------------------------

for i = 1:nStations

    text( ...
        ax2, ...
        TotalSort(i)+0.4, ...
        i, ...
        sprintf('%d',TotalSort(i)), ...
        'VerticalAlignment','middle', ...
        'HorizontalAlignment','left', ...
        'FontSize',10.5, ...
        'FontWeight','bold', ...
        'Color','k');

end


%% ------------------------------------------------------------------------
% Add shared percentage inside shared section
%% ------------------------------------------------------------------------

for i = 1:nStations


    if SharedSort(i) == 0
        continue
    end


    pct = ...
        100 * SharedSort(i) / TotalSort(i);


    xpos = ...
        UniqueSort(i) + SharedSort(i)/2;


    if SharedSort(i) >= 3

        text( ...
            ax2, ...
            xpos, ...
            i, ...
            sprintf('%.0f%%',pct), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontSize',9.5, ...
            'FontWeight','bold', ...
            'Color','k');

    end

end


legend( ...
    ax2, ...
    {'Station-specific','Shared with another station'}, ...
    'Location','southoutside', ...
    'Orientation','horizontal', ...
    'Box','off', ...
    'FontSize',11);


grid(ax2,'on');

ax2.GridLineStyle = ':';

ax2.GridAlpha = 0.15;


text( ...
    ax2, ...
    0.02, ...
    0.98, ...
    '(b)', ...
    'Units','normalized', ...
    'VerticalAlignment','top', ...
    'FontSize',16, ...
    'FontWeight','bold');


%% ========================================================================
% EXPORT FIGURE 1
%% ========================================================================

out1PNG = fullfile( ...
    OUT_DIR, ...
    'Landslide_Overlap_20km_Multiplicity_and_Stations.png');


out1TIF = fullfile( ...
    OUT_DIR, ...
    'Landslide_Overlap_20km_Multiplicity_and_Stations.tiff');


exportgraphics( ...
    fig1, ...
    out1PNG, ...
    'Resolution',600);


exportgraphics( ...
    fig1, ...
    out1TIF, ...
    'Resolution',600);


%% ========================================================================
% 9. PAIRWISE STATION-OVERLAP MATRIX
%% ========================================================================

OverlapMatrix = ...
    zeros(nStations,nStations);


%% ------------------------------------------------------------------------
% Each unique physical event:
% identify all associated stations.
%% ------------------------------------------------------------------------

for e = 1:nPhysicalEvents


    idx = ...
        eventGroup == e;


    sites = unique( ...
        string(Pairs.Station(idx)), ...
        'stable');


    if numel(sites) < 2
        continue
    end


    siteID = ...
        zeros(numel(sites),1);


    for q = 1:numel(sites)

        siteID(q) = ...
            find(Station == sites(q),1);

    end


    %% --------------------------------------------------------------------
    % Add one count for every pair sharing this event
    %% --------------------------------------------------------------------

    for a = 1:numel(siteID)-1

        for b = a+1:numel(siteID)


            s1 = siteID(a);

            s2 = siteID(b);


            OverlapMatrix(s1,s2) = ...
                OverlapMatrix(s1,s2) + 1;


            OverlapMatrix(s2,s1) = ...
                OverlapMatrix(s2,s1) + 1;

        end

    end

end


%% ------------------------------------------------------------------------
% Diagonal intentionally set to NaN
%% ------------------------------------------------------------------------

for s = 1:nStations

    OverlapMatrix(s,s) = NaN;

end


%% ========================================================================
% FIGURE 2 -- PAIRWISE OVERLAP HEATMAP
%% ========================================================================

fig2 = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 27 24], ...
    'Renderer','painters');


ax3 = axes(fig2);


imagesc( ...
    ax3, ...
    OverlapMatrix);


set( ...
    ax3, ...
    'YDir','normal');


%% ------------------------------------------------------------------------
% Sequential publication colormap
%% ------------------------------------------------------------------------

anchor = [ ...
    247 252 253
    204 236 230
    102 194 164
    44 162 95
    0 109 44] ./ 255;


xi = linspace( ...
    0,1,size(anchor,1));


xq = linspace( ...
    0,1,256);


cmap = interp1( ...
    xi, ...
    anchor, ...
    xq, ...
    'pchip');


colormap( ...
    ax3, ...
    cmap);


maxOverlap = ...
    max(OverlapMatrix(:),[],'omitnan');


if maxOverlap < 1
    maxOverlap = 1;
end


clim( ...
    ax3, ...
    [0 maxOverlap]);


%% ------------------------------------------------------------------------
% Cell annotations
%% ------------------------------------------------------------------------

for i = 1:nStations

    for j = 1:nStations


        value = ...
            OverlapMatrix(i,j);


        if ~isfinite(value) || value == 0
            continue
        end


        text( ...
            ax3, ...
            j, ...
            i, ...
            sprintf('%d',value), ...
            'HorizontalAlignment','center', ...
            'VerticalAlignment','middle', ...
            'FontSize',8.5, ...
            'FontWeight','bold', ...
            'Color','k');

    end

end


set( ...
    ax3, ...
    'XTick',1:nStations, ...
    'XTickLabel',Station, ...
    'YTick',1:nStations, ...
    'YTickLabel',Station, ...
    'FontSize',10, ...
    'FontWeight','bold', ...
    'TickLength',[0 0], ...
    'LineWidth',1, ...
    'XColor','k', ...
    'YColor','k', ...
    'Box','on');


xtickangle( ...
    ax3, ...
    50);


xlabel( ...
    ax3, ...
    'Station', ...
    'FontSize',14, ...
    'FontWeight','bold');


ylabel( ...
    ax3, ...
    'Station', ...
    'FontSize',14, ...
    'FontWeight','bold');


cb = colorbar(ax3);


cb.Label.String = ...
    'Number of shared physical landslide events';


cb.Label.FontSize = 13;

cb.Label.FontWeight = 'bold';

cb.FontSize = 11;

cb.FontWeight = 'bold';


%% ========================================================================
% EXPORT FIGURE 2
%% ========================================================================

out2PNG = fullfile( ...
    OUT_DIR, ...
    'Landslide_Overlap_20km_Pairwise_Heatmap.png');


out2TIF = fullfile( ...
    OUT_DIR, ...
    'Landslide_Overlap_20km_Pairwise_Heatmap.tiff');


exportgraphics( ...
    fig2, ...
    out2PNG, ...
    'Resolution',600);


exportgraphics( ...
    fig2, ...
    out2TIF, ...
    'Resolution',600);


%% ========================================================================
% 10. WRITE A SMALL OVERLAP SUMMARY EXCEL
%% ========================================================================

Summary = table( ...
    N_uniquePhysical, ...
    N_singleStation, ...
    N_sharedPhysical, ...
    pctSharedPhysical, ...
    N_stationAssignments, ...
    N_extraAssignments, ...
    maxMultiplicity, ...
    'VariableNames',{ ...
    'Unique_physical_landslides', ...
    'Single_station_events', ...
    'Shared_physical_events', ...
    'Shared_events_percent', ...
    'Total_station_event_assignments', ...
    'Extra_assignments_due_to_overlap', ...
    'Maximum_number_of_stations_per_event'});


outExcel = fullfile( ...
    OUT_DIR, ...
    'Landslide_Overlap_20km_Figure_Summary.xlsx');


writetable( ...
    Summary, ...
    outExcel, ...
    'Sheet','Summary');


MultiplicityTable = table( ...
    multiplicityLevels(:), ...
    multiplicityCount(:), ...
    'VariableNames',{ ...
    'Number_of_stations', ...
    'Number_of_physical_landslides'});


writetable( ...
    MultiplicityTable, ...
    outExcel, ...
    'Sheet','Multiplicity');


PairwiseTable = ...
    array2table( ...
    OverlapMatrix, ...
    'VariableNames', ...
    matlab.lang.makeValidName(cellstr(Station)));


PairwiseTable = addvars( ...
    PairwiseTable, ...
    Station, ...
    'Before',1, ...
    'NewVariableNames','Station');


writetable( ...
    PairwiseTable, ...
    outExcel, ...
    'Sheet','Pairwise_overlap');


%% ========================================================================
% FINAL MESSAGE
%% ========================================================================

fprintf('\n');
fprintf('=============================================================\n');
fprintf(' FIGURES WRITTEN\n');
fprintf('=============================================================\n');

fprintf('Figure 1:\n%s\n\n',out1PNG);

fprintf('Figure 2:\n%s\n\n',out2PNG);

fprintf('Summary Excel:\n%s\n',outExcel);

fprintf('=============================================================\n');