
%% ========================================================================
% FUNCTION 7 -- BUILD METADATA WORKBOOK TABLE
%% ========================================================================

function Meta = buildMetadataTable( ...
    Lunique, ...
    uDate, ...
    R, ...
    StationName, ...
    StationID)


    keep = ...
        R.finalStationIndex > 0;


    idx = find(keep);


    MetaOriginal = ...
        Lunique(idx,:);


    siteIndex = ...
        R.finalStationIndex(idx);


    AssignedStation = ...
        StationName(siteIndex);


    AssignedIMD_ID = ...
        StationID(siteIndex);


    GreatCircleDistance_km = ...
        R.nearestDistance(idx);


    AnalysisRadius_km = ...
        repmat( ...
        R.radiusKm, ...
        numel(idx), ...
        1);


    NumberOfStationsWithinRadius = ...
        R.candidateStationN(idx);


    WasInOverlappingBuffers = ...
        NumberOfStationsWithinRadius > 1;


    EventDate = ...
        uDate(idx);


    EventYear = year(EventDate);

    EventMonth = month(EventDate);

    EventDay = day(EventDate);


    %% --------------------------------------------------------------------
    % Put analysis information FIRST
    %% --------------------------------------------------------------------

    AnalysisColumns = table( ...
        AssignedStation, ...
        AssignedIMD_ID, ...
        GreatCircleDistance_km, ...
        AnalysisRadius_km, ...
        NumberOfStationsWithinRadius, ...
        WasInOverlappingBuffers, ...
        EventDate, ...
        EventYear, ...
        EventMonth, ...
        EventDay);


    Meta = ...
        [AnalysisColumns MetaOriginal];


    %% --------------------------------------------------------------------
    % Sort by station and date
    %% --------------------------------------------------------------------

    Meta = sortrows( ...
        Meta, ...
        {'AssignedStation','EventDate'});

end
