%% ========================================================================
% Plot_radius_Landslide_Overlap.m
%
% PURPOSE
% -------------------------------------------------------------------------
% Professional figure showing landslide-event sharing among the 21
% station buffers for the station-radius analysis.
%
% Each bar represents all landslide events associated with a station:
%
%   1. Unique to that station's station-radius buffer
%   2. Shared with one or more other station buffers
%
% Catalogue-level duplicates were already removed BEFORE this analysis.
%
% ========================================================================

clc;
clear;
close all;


%% ========================================================================
% 1. INPUT / OUTPUT
%% ========================================================================

ROOT = ...
    fullfile(neh_root(),'step_0_landslide_filtering');


COUNT_XLSX = fullfile( ...
    ROOT, ...
    'Station_Landslide_Counts_radius_ALLOW_OVERLAP.xlsx');


OUT_PNG = fullfile( ...
    ROOT, ...
    'Landslide_Overlap_radius_Station_Buffers.png');


OUT_TIF = fullfile( ...
    ROOT, ...
    'Landslide_Overlap_radius_Station_Buffers.tiff');


%% ========================================================================
% 2. READ STATION COUNTS
%% ========================================================================

T = readtable( ...
    COUNT_XLSX, ...
    'Sheet','Station_counts', ...
    'VariableNamingRule','preserve');


Station = string(T.Station);

Total = ...
    T.Events_within_radius;

UniqueOnly = ...
    T.Events_unique_to_this_station_buffer;

Shared = ...
    T.Events_also_within_other_station_buffers;


%% ========================================================================
% 3. QUALITY CONTROL
%% ========================================================================

if any((UniqueOnly + Shared) ~= Total)

    error( ...
        'QC failed: Unique + Shared does not equal Total for all stations.');

end


%% ========================================================================
% 4. SORT STATIONS BY TOTAL LANDSLIDE COUNT
%% ========================================================================

[TotalSort,ord] = sort( ...
    Total, ...
    'descend');


StationSort = ...
    Station(ord);


UniqueSort = ...
    UniqueOnly(ord);


SharedSort = ...
    Shared(ord);


%% ========================================================================
% 5. SUMMARY
%% ========================================================================

fprintf('\n');
fprintf('=============================================================\n');
fprintf(' station-radius LANDSLIDE OVERLAP SUMMARY\n');
fprintf('=============================================================\n');

fprintf( ...
    'Total station-event assignments : %d\n', ...
    sum(Total));


fprintf( ...
    'Non-overlapping assignments     : %d\n', ...
    sum(UniqueOnly));


fprintf( ...
    'Shared assignments              : %d\n', ...
    sum(Shared));


fprintf( ...
    'Stations with shared events     : %d / %d\n', ...
    sum(Shared > 0), ...
    height(T));


fprintf('=============================================================\n\n');


%% ========================================================================
% 6. PROFESSIONAL STACKED HORIZONTAL BAR
%% ========================================================================

fig = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[2 2 25 21], ...
    'Renderer','painters');


ax = axes(fig);

hold(ax,'on');


%% ------------------------------------------------------------------------
% Data matrix
%% ------------------------------------------------------------------------

Y = [UniqueSort SharedSort];


%% ------------------------------------------------------------------------
% Stacked horizontal bar
%% ------------------------------------------------------------------------

b = barh( ...
    ax, ...
    Y, ...
    'stacked', ...
    'BarWidth',0.72);


% Restrained manuscript colours
b(1).FaceColor = [0.72 0.82 0.91];
b(1).EdgeColor = [0.20 0.20 0.20];
b(1).LineWidth = 0.65;

b(2).FaceColor = [0.82 0.32 0.28];
b(2).EdgeColor = [0.20 0.20 0.20];
b(2).LineWidth = 0.65;


%% ========================================================================
% 7. LABEL EXACT SHARED COUNT
%% ========================================================================

maxTotal = max(TotalSort);

offset = max(0.5,0.012*maxTotal);


for i = 1:numel(StationSort)

    %% --------------------------------------------------------------------
    % Total count at end of each bar
    %% --------------------------------------------------------------------

    text( ...
        ax, ...
        TotalSort(i) + offset, ...
        i, ...
        sprintf('%d',TotalSort(i)), ...
        'HorizontalAlignment','left', ...
        'VerticalAlignment','middle', ...
        'FontSize',11.5, ...
        'FontWeight','bold', ...
        'Color','k');


    %% --------------------------------------------------------------------
    % Shared-event count inside red segment
    %% --------------------------------------------------------------------

    if SharedSort(i) > 0

        xSharedCentre = ...
            UniqueSort(i) + SharedSort(i)/2;


        % Place count inside segment when reasonably wide
        if SharedSort(i) >= 3

            text( ...
                ax, ...
                xSharedCentre, ...
                i, ...
                sprintf('%d',SharedSort(i)), ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'FontSize',10.5, ...
                'FontWeight','bold', ...
                'Color','w');

        else

            % For tiny shared segments place label above/right
            text( ...
                ax, ...
                UniqueSort(i) + SharedSort(i) + 0.25, ...
                i, ...
                sprintf('%d',SharedSort(i)), ...
                'HorizontalAlignment','left', ...
                'VerticalAlignment','middle', ...
                'FontSize',10, ...
                'FontWeight','bold', ...
                'Color',[0.65 0.10 0.08]);

        end

    end

end


%% ========================================================================
% 8. AXIS FORMATTING
%% ========================================================================

set( ...
    ax, ...
    'YDir','reverse', ...
    'YTick',1:numel(StationSort), ...
    'YTickLabel',StationSort, ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'XColor','k', ...
    'YColor','k', ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'Layer','top');


xlabel( ...
    ax, ...
    'Number of landslide events within station radius', ...
    'FontSize',15, ...
    'FontWeight','bold', ...
    'Color','k');


xlim( ...
    ax, ...
    [0 maxTotal + max(4,0.10*maxTotal)]);


%% ========================================================================
% 9. GRID
%% ========================================================================

grid(ax,'on');

ax.YGrid = 'off';

ax.XGrid = 'on';

ax.GridLineStyle = ':';

ax.GridAlpha = 0.20;


%% ========================================================================
% 10. LEGEND
%% ========================================================================

lgd = legend( ...
    b, ...
    {'Unique to station buffer', ...
     'Shared with other station buffer(s)'}, ...
    'Location','southoutside', ...
    'Orientation','horizontal');


lgd.FontSize = 11.5;

lgd.FontWeight = 'bold';

lgd.Box = 'off';


% No overall title for manuscript figure


%% ========================================================================
% 11. EXPORT
%% ========================================================================

exportgraphics( ...
    fig, ...
    OUT_PNG, ...
    'Resolution',600);


exportgraphics( ...
    fig, ...
    OUT_TIF, ...
    'Resolution',600);


fprintf('Figure written:\n%s\n',OUT_PNG);


%% ========================================================================
% 12. OPTIONAL: OVERLAP MULTIPLICITY HISTOGRAM
%
% This second figure answers:
% "How many physical landslides are shared by 2, 3, 4... stations?"
%% ========================================================================

Overlap = readtable( ...
    COUNT_XLSX, ...
    'Sheet','Overlap_events', ...
    'VariableNamingRule','preserve');


nStationsPerEvent = ...
    Overlap.Number_of_stations;


values = unique( ...
    nStationsPerEvent);


freq = zeros( ...
    size(values));


for i = 1:numel(values)

    freq(i) = ...
        sum(nStationsPerEvent == values(i));

end


fig2 = figure( ...
    'Color','w', ...
    'Units','centimeters', ...
    'Position',[3 3 17 13], ...
    'Renderer','painters');


ax2 = axes(fig2);


bar( ...
    ax2, ...
    values, ...
    freq, ...
    0.65, ...
    'FaceColor',[0.72 0.38 0.34], ...
    'EdgeColor','k', ...
    'LineWidth',0.8);


hold(ax2,'on');


%% ------------------------------------------------------------------------
% Add exact frequencies
%% ------------------------------------------------------------------------

for i = 1:numel(values)

    text( ...
        ax2, ...
        values(i), ...
        freq(i) + max(freq)*0.02, ...
        sprintf('%d',freq(i)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',12, ...
        'FontWeight','bold', ...
        'Color','k');

end


set( ...
    ax2, ...
    'XTick',values, ...
    'FontSize',12, ...
    'FontWeight','bold', ...
    'LineWidth',1.0, ...
    'TickDir','out', ...
    'Box','off', ...
    'XColor','k', ...
    'YColor','k');


xlabel( ...
    ax2, ...
    'Number of station buffers containing the same landslide', ...
    'FontSize',14, ...
    'FontWeight','bold');


ylabel( ...
    ax2, ...
    'Number of shared landslide events', ...
    'FontSize',14, ...
    'FontWeight','bold');


grid(ax2,'on');

ax2.XGrid = 'off';

ax2.YGrid = 'on';

ax2.GridAlpha = 0.18;

ax2.GridLineStyle = ':';


OUT_HIST_PNG = fullfile( ...
    ROOT, ...
    'Landslide_Overlap_Multiplicity_radius.png');


OUT_HIST_TIF = fullfile( ...
    ROOT, ...
    'Landslide_Overlap_Multiplicity_radius.tiff');


exportgraphics( ...
    fig2, ...
    OUT_HIST_PNG, ...
    'Resolution',600);


exportgraphics( ...
    fig2, ...
    OUT_HIST_TIF, ...
    'Resolution',600);


fprintf( ...
    '\nOverlap histogram written:\n%s\n', ...
    OUT_HIST_PNG);