%% ========================================================================
% FUNCTION 2
% PLOT ONE RADIUS PANEL
%% ========================================================================

function plotRadiusPanel( ...
    ax, ...
    UniqueData, ...
    SharedData, ...
    TotalData, ...
    StationLabels, ...
    uniqueColor, ...
    sharedColor, ...
    edgeColor, ...
    xMax, ...
    showStationLabels)


    n = ...
        numel(TotalData);


    hold(ax,'on');


    %% --------------------------------------------------------------------
    % STACKED DATA
    %% --------------------------------------------------------------------

    Y = [ ...
        UniqueData ...
        SharedData];


    b = barh( ...
        ax, ...
        Y, ...
        'stacked', ...
        'BarWidth',0.70);


    %% --------------------------------------------------------------------
    % Colours
    %% --------------------------------------------------------------------

    b(1).FaceColor = ...
        uniqueColor;


    b(1).EdgeColor = ...
        edgeColor;


    b(1).LineWidth = ...
        0.65;


    b(2).FaceColor = ...
        sharedColor;


    b(2).EdgeColor = ...
        edgeColor;


    b(2).LineWidth = ...
        0.65;


    %% --------------------------------------------------------------------
    % TOTAL COUNTS
    %% --------------------------------------------------------------------

    offset = ...
        max(0.5,0.008*xMax);


    for i = 1:n


        text( ...
            ax, ...
            TotalData(i)+offset, ...
            i, ...
            sprintf('%d',TotalData(i)), ...
            'HorizontalAlignment','left', ...
            'VerticalAlignment','middle', ...
            'FontSize',10.5, ...
            'FontWeight','bold', ...
            'Color','k');


        %% ----------------------------------------------------------------
        % Shared-event COUNT inside red segment
        %
        % This directly answers reviewer concern.
        %% ----------------------------------------------------------------

        if SharedData(i) >= 4


            xShared = ...
                UniqueData(i) + ...
                SharedData(i)/2;


            text( ...
                ax, ...
                xShared, ...
                i, ...
                sprintf('%d',SharedData(i)), ...
                'HorizontalAlignment','center', ...
                'VerticalAlignment','middle', ...
                'FontSize',9.5, ...
                'FontWeight','bold', ...
                'Color','w');

        end

    end


    %% --------------------------------------------------------------------
    % Axis
    %% --------------------------------------------------------------------

    set( ...
        ax, ...
        'YDir','reverse', ...
        'YTick',1:n, ...
        'FontSize',11, ...
        'FontWeight','bold', ...
        'LineWidth',0.9, ...
        'TickDir','out', ...
        'Box','off', ...
        'XColor','k', ...
        'YColor','k', ...
        'Layer','top');


    %% --------------------------------------------------------------------
    % Only first panel gets station names
    %% --------------------------------------------------------------------

    if showStationLabels

        ax.YTickLabel = ...
            StationLabels;

    else

        ax.YTickLabel = ...
            [];

    end


    xlim( ...
        ax, ...
        [0 xMax]);


    ylim( ...
        ax, ...
        [0.3 n+0.7]);


    %% --------------------------------------------------------------------
    % Grid
    %% --------------------------------------------------------------------

    grid(ax,'on');


    ax.XGrid = 'on';

    ax.YGrid = 'off';


    ax.GridLineStyle = ':';

    ax.GridAlpha = 0.16;

end