function writeStationTXT( ...
    outDir, ...
    stationName, ...
    stationID, ...
    T, ...
    dt, ...
    distanceKm)


    safeName = regexprep( ...
        char(stationName), ...
        '[^\w\-]', ...
        '_');


    fileName = sprintf( ...
        '%s_%s_landslides.txt', ...
        safeName, ...
        char(stationID));


    outFile = fullfile( ...
        outDir, ...
        fileName);


    fid = fopen(outFile,'w');


    if fid == -1

        error( ...
            'Cannot create TXT file: %s', ...
            outFile);

    end


    cleanupObj = ...
        onCleanup(@() fclose(fid)); %#ok<NASGU>


    if isempty(T)
        return
    end


    lon = toNumeric(T.longitude);
    lat = toNumeric(T.latitude);


    [dt,ord] = sort(dt);


    lon = lon(ord);
    lat = lat(ord);

    distanceKm = ...
        distanceKm(ord);


    for k = 1:numel(dt)

        fprintf( ...
            fid, ...
            '%.6f,%.6f,%.12f,%d,%d,%d\n', ...
            lon(k), ...
            lat(k), ...
            distanceKm(k), ...
            year(dt(k)), ...
            month(dt(k)), ...
            day(dt(k)));

    end

end